/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.neu.csye6200.view;

import edu.neu.csye6200.controller.BookingController;
import edu.neu.csye6200.controller.ReviewController;
import edu.neu.csye6200.controller.ShowController;
import edu.neu.csye6200.controller.TheatreController;
import edu.neu.csye6200.model.Booking;
import edu.neu.csye6200.model.Customer;
import edu.neu.csye6200.model.Movie;
import edu.neu.csye6200.model.Review;
import edu.neu.csye6200.model.Theatre;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;

/**
 *
 * @author yashl
 */
public class MovieDetailScreen extends javax.swing.JFrame {

    /**
     * Creates new form MovieDetailScreen
     */
    private Movie movie;
    
    private String selectedTheatre;
    private String selectedShow;
    private int seats;
    private int showId;
    private Customer user;
    public Map<String, Integer> showTimes = new HashMap<>();
    public MovieDetailScreen() {
        initComponents();
        setDetailsOnScreen();
        leftSidePanel();
    }
    
    public void setDetailsOnScreen() {
        //Getting list of Theatre
        TheatreController theatreList = new TheatreController();
        List<String> theatres = theatreList.getTheatresForMovie(this.movie.getTitle());
        String[] listOfTheatres = new String[theatres.size()];
      
        for(int i = 0; i < listOfTheatres.length; i++) {
            listOfTheatres[i] = theatres.get(i);
            System.out.print("Arr: " + listOfTheatres[i]);
        }
        theatreDropdown.setModel(new DefaultComboBoxModel<>(listOfTheatres));
        //theatreDropdown.setSelectedIndex(0);
        movieDetailsPanel.add(theatreDropdown); // Add theatreDropdown to the movieDetailsPanel
        
        
        
        
        //Setting Showtimedropdown to default times
        String[] showtimes = {"- Select -"};
        showTimeDropdown.setModel(new DefaultComboBoxModel<>(showtimes));
        showTimeDropdown.setSelectedIndex(0);
        movieDetailsPanel.add(showTimeDropdown); // Add showTimeDropdown to the movieDetailsPanel
        
        ShowController show = new ShowController();
        
        String theatreName= theatreDropdown.getSelectedItem().toString();

        Map<Integer, String> theatreVmovieID = show.getShowsOnScreen(theatreName, this.movie.getId());
        
        for (Map.Entry<Integer, String> set :
             theatreVmovieID.entrySet()) {
 
            // Printing all elements of a Map
            System.out.println(set.getKey() + " = "
                               + set.getValue());
        }

    }
    
    public void leftSidePanel(){

        movieName.setText(this.movie.getTitle());
        movieDuration.setText(Integer.toString(this.movie.getDuration()) + "min");
        movieGenre.setText(this.movie.getGenre());
        ReviewController revCon = new ReviewController();
        Review rev = revCon.getReviewById(this.movie.getId());
        movieReview.setText(rev.getComment());
        pack();
        
    }

    MovieDetailScreen(Movie selectedMovie , Customer user) {
        this.movie = selectedMovie;
        this.user = user;
        initComponents();
        setDetailsOnScreen();
        leftSidePanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movieDetailsPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        movieName = new javax.swing.JLabel();
        movieGenre = new javax.swing.JLabel();
        movieReview = new javax.swing.JLabel();
        movieDuration = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        showTimeDropdown = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        theatreDropdown = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        selectedSeat = new javax.swing.JSpinner();
        bookTicketBtn = new javax.swing.JButton();
        setTheatre = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        confirmSeatsBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        movieDetailsPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(7, 59, 76));
        jPanel2.setPreferredSize(new java.awt.Dimension(488, 400));

        movieName.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        movieName.setForeground(new java.awt.Color(255, 255, 102));
        movieName.setText("Default Movie Name");

        movieGenre.setBackground(new java.awt.Color(51, 51, 51));
        movieGenre.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        movieGenre.setForeground(new java.awt.Color(204, 204, 204));
        movieGenre.setText("Drama");

        movieReview.setBackground(new java.awt.Color(51, 51, 51));
        movieReview.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        movieReview.setForeground(new java.awt.Color(204, 204, 204));
        movieReview.setText("4.5 out of 5");

        movieDuration.setBackground(new java.awt.Color(51, 51, 51));
        movieDuration.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        movieDuration.setForeground(new java.awt.Color(204, 204, 204));
        movieDuration.setText("150 mins");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Movie Details");

        jLabel6.setIcon(new javax.swing.ImageIcon("F:\\Classwork\\CSYE-6200 OOD\\Project\\AllNew\\final-project-final-group-14\\src\\images\\book-image-01.png")); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(180, 180));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Duration: ");

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Genre: ");

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Ratings: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(movieName)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(movieGenre))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(movieDuration)
                            .addComponent(movieReview))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addGap(56, 56, 56)
                .addComponent(movieName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movieGenre)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(movieDuration))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(movieReview))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        showTimeDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        showTimeDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTimeDropdownActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel1.setText("Show Times");

        theatreDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        theatreDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theatreDropdownActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setText("Theatre");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setText("Select Seats");

        bookTicketBtn.setBackground(new java.awt.Color(7, 59, 76));
        bookTicketBtn.setForeground(new java.awt.Color(255, 255, 255));
        bookTicketBtn.setText("Book Tickets");
        bookTicketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookTicketBtnActionPerformed(evt);
            }
        });

        setTheatre.setBackground(new java.awt.Color(7, 59, 76));
        setTheatre.setForeground(new java.awt.Color(255, 255, 255));
        setTheatre.setText("Confirm Theatre");
        setTheatre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setTheatreActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(7, 59, 76));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Confirm Show");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        confirmSeatsBtn.setBackground(new java.awt.Color(7, 59, 76));
        confirmSeatsBtn.setForeground(new java.awt.Color(255, 255, 255));
        confirmSeatsBtn.setText("Confirm Seats");
        confirmSeatsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmSeatsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout movieDetailsPanelLayout = new javax.swing.GroupLayout(movieDetailsPanel);
        movieDetailsPanel.setLayout(movieDetailsPanelLayout);
        movieDetailsPanelLayout.setHorizontalGroup(
            movieDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movieDetailsPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(movieDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showTimeDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(movieDetailsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(selectedSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bookTicketBtn)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(theatreDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setTheatre)
                    .addComponent(jButton2)
                    .addComponent(confirmSeatsBtn))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        movieDetailsPanelLayout.setVerticalGroup(
            movieDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
            .addGroup(movieDetailsPanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(theatreDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(setTheatre)
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showTimeDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jButton2)
                .addGap(53, 53, 53)
                .addGroup(movieDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(selectedSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(confirmSeatsBtn)
                .addGap(39, 39, 39)
                .addComponent(bookTicketBtn)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(movieDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(movieDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showTimeDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTimeDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showTimeDropdownActionPerformed

    private void theatreDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theatreDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_theatreDropdownActionPerformed

    private void bookTicketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTicketBtnActionPerformed
        // TODO add your handling code here:
        int showID = this.showId;
        Date booking = new Date();
        
        Booking book = new Booking(showID, booking, user.getId());
        
        BookingController bookCon = new BookingController();
        
        bookCon.addBooking(book, seats);
        
        BookingReceiptFrame_New re = new BookingReceiptFrame_New(this.user, book, this.movie.getTitle());
        this.setVisible(false);
        re.setVisible(true);
        
        
    }//GEN-LAST:event_bookTicketBtnActionPerformed

    private void setTheatreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setTheatreActionPerformed
        // TODO add your handling code here:
        ShowController show = new ShowController();
        
        String theatreName= theatreDropdown.getSelectedItem().toString();

        this.selectedTheatre = theatreName;
        
        Map<Integer, String> theatreVmovieID = show.getShowsOnScreen(theatreName, this.movie.getId());
        
        Map<String, Integer> showTimes = new HashMap<>();
        List<String> li = new ArrayList<>();
        for (Map.Entry<Integer, String> set :
             theatreVmovieID.entrySet()) {
            // Printing all elements of a Map
            System.out.println(set.getKey() + " = "
                               + set.getValue());

            this.showTimes.put(set.getValue(), set.getKey());
            li.add(set.getValue());
            
        }
        
        String[] showtimeArr = li.toArray(new String[0]);
        
        showTimeDropdown.setModel(new DefaultComboBoxModel<>(showtimeArr));
    }//GEN-LAST:event_setTheatreActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            String showTime = showTimeDropdown.getSelectedItem().toString();
            
            String[] tmp = showTime.split("=");
            for (Map.Entry<String, Integer> set :
             this.showTimes.entrySet()) {
            // Printing all elements of a Map
            System.out.println(set.getKey() + " = "
                               + set.getValue());

        }

            System.out.print("showId:" + showTime);

            this.showId = showTimes.get(showTime);
            System.out.println("showId:" + this.showId);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void confirmSeatsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmSeatsBtnActionPerformed
        // TODO add your handling code here:
        
        System.out.println("sasd" + selectedSeat.getValue());
        String value = selectedSeat.getValue().toString();
        System.out.println("sasd>  " + value);
        this.seats = Integer.parseInt(value);
        
    }//GEN-LAST:event_confirmSeatsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieDetailScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieDetailScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieDetailScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieDetailScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieDetailScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookTicketBtn;
    private javax.swing.JButton confirmSeatsBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel movieDetailsPanel;
    private javax.swing.JLabel movieDuration;
    private javax.swing.JLabel movieGenre;
    private javax.swing.JLabel movieName;
    private javax.swing.JLabel movieReview;
    private javax.swing.JSpinner selectedSeat;
    private javax.swing.JButton setTheatre;
    private javax.swing.JComboBox<String> showTimeDropdown;
    private javax.swing.JComboBox<String> theatreDropdown;
    // End of variables declaration//GEN-END:variables
}
